appliweb/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LogoutView


urlpatterns = [
    path('', views.home, name='home'),
    path('sujets/', views.liste_sujets, name='liste_sujets'),
    path('pricing/', views.pricing, name='pricing'),
    path('propos/', views.propos, name='propos'),
    path('contact/', views.envoyer_message, name='contact'),
    path('search/', views.search, name='search'),
    path('rechercher/', views.recherche_sujet, name='recherche_sujet'),
    path('sujets/<int:sujet_id>/', views.detail_sujet, name='detail_sujet'),
    path('ajouter/', views.ajouter_sujet, name='ajouter_sujet'),
] 

projetweb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


from appliweb import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('appliweb.urls')), # Include urls from 'myfaxes' app
    path('', include('usersapp.urls')), # Include urls from 'usersapp' app
    path('', include('django.contrib.auth.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'appliweb.views.custom_page_not_found_view'
handler500 = 'appliweb.views.custom_error_view'
handler403 = 'appliweb.views.custom_permission_denied_view'
handler400 = 'appliweb.views.custom_bad_request_view'

appliweb/models.py
from django.db import models

class Sujet(models.Model):
    TYPE_SUJET_CHOICES = [
        ('TD', 'Travaux Dirigés'),
        ('TPE', 'Travaux Pratiques Encadrés'),
        ('CC', 'Contrôle Continu'),
        ('EXAM', 'Examen'),
    ]
    NIVEAU_CHOICES = [
        ('Niveau 1', 'Niveau 1'),
        ('Niveau 2', 'Niveau 2'),
        ('Niveau 3', 'Niveau 3'),
    ]
    FILIERE_CHOICES = [
        ('Informatique Fondamentale', 'Informatique Fondamentale'),
        ('Informatique et Gestion des entreprises', 'Informatique et Gestion des entreprises'),
        ('Mathématiques', 'Mathématiques'),
        ('Physique', 'Physique'),
        ('Chimie', 'Chimie'),
        ('Science Biologie', 'Science Biologie'),
        ('Science de la terre', 'Science de la terre'),

    ]
    
    nom_cours = models.CharField(max_length=100,)
    code_cours = models.CharField(max_length=10)
    titre = models.CharField(max_length=200)
    type_sujet = models.CharField(max_length=4, choices=TYPE_SUJET_CHOICES)
    annee = models.IntegerField()
    niveau = models.CharField(max_length=10, choices=NIVEAU_CHOICES)
    filiere = models.CharField(max_length=100, choices=FILIERE_CHOICES)
    cours = models.CharField(max_length=100, default='Cours')
    fichier = models.FileField(upload_to='sujets/')

    def __str__(self):
        return f"{self.code_cours} - {self.nom_cours} : {self.titre} ({self.get_type_sujet_display()})"

templates/ajouter_sujet.html
{% extends 'base.html' %}

{% block title %}Ajouter un Sujet{% endblock %}

{% block content %}
<div class="container mt-4 text-light">
    <div class="row">
        <div class="col-lg-8 offset-lg-2">
            <h2 class="mb-4">Ajouter un Nouveau Sujet</h2>
            <form method="post" enctype="multipart/form-data" class="needs-validation" novalidate>
                {% csrf_token %}
                <div class="form-row">
                    {% for field in form %}
                        <div class="form-group col-md-6">
                            {{ field.label_tag }}
                            {{ field }}
                            {% if field.help_text %}
                                <small class="form-text text-muted">{{ field.help_text }}</small>
                            {% endif %}
                            {% for error in field.errors %}
                                <div class="invalid-feedback">
                                    {{ error }}
                                </div>
                            {% endfor %}
                        </div>
                    {% endfor %}
                </div>
                <button type="submit" class="btn btn-success">Ajouter le sujet</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}My Fax{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css">
    <link rel="stylesheet" href="{% static 'css/bootstrap-grid.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <style>
        body {
            background: url("{% static 'img/fond1.jpg' %}") center/cover no-repeat fixed;
        }    
    </style>
</head>

<body>
    <!-- Barre de navigation optimisée -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
        <div class="container">
            <a class="navbar-brand w-25 h-25" href="{% url 'home' %}"><img src="{% static 'img/logo.png' %}"
                    alt="My Fax" class="logo img-fluid w-25 h-25"></a>
            <button class="navbar-toggler shadow-none" type="button" data-toggle="collapse" data-target="#navbarContent"
                aria-controls="navbarContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarContent">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'search' %}">Rechercher</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'pricing' %}">Tarifs</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'propos' %}">A propos</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'liste_sujets' %}">Sujets</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'contact' %}">Contact</a>
                    </li>
                    {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <a class="btn btn-outline-light btn-sm m-2" href="{% url 'logout' %}"
                            role="button">Déconnexion</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="btn btn-outline-light btn-sm m-2" href="{% url 'register' %}"
                            role="button">Inscription</a>
                    </li>
                    <li class="nav-item">
                        <a class="btn btn-light btn-sm m-2" href="{% url 'login' %}?next={{ request.path }}"
                            role="button">Connexion</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>


    <!-- Contenu principal -->
    <main role="main" class="main py-4 pt-5 mt-5">
        <div class="container">

            <!-- Section des notifications -->
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }}" role="alert">
                {{ message }}
            </div>
            {% endfor %}

            {% block content %}{% endblock %}

        </div>
    </main>

    <!-- Pied de page élégant -->
    <footer class="footer mt-auto py-3 bg-primary">
        <div class="container text-center">
            <span class="text-white">&copy; 2024 - My Fax. Tous droits réservés.</span>
        </div>
    </footer>

    <!-- Scripts Bootstrap via CDN -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
    <script src="{% static 'js/script.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/jquery.min.js' %}"></script>
</body>

</html>

templates/contact.html
{% extends 'base.html' %}

{% block content %}
<div class="row justify-content-center">
    <div class="col-lg-8">
        <div class="contact-container text-light bg-light p-5 border rounded-3 bg-opacity-10">
            <h2 class="contact-title text-center text-primary mb-4">Contactez-nous</h2>
            <p class="contact-text text-light text-center mb-5">Nous sommes là pour répondre à toutes vos questions. Remplissez le formulaire ci-dessous et nous vous répondrons dans les plus brefs délais.</p>
            
            <form action="{% url 'contact' %}" method="post" class="contact-form">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="name" class="form-label">Nom</label>
                    <input type="text" id="name" name="name" class="form-control shadow-none" placeholder="Votre Nom" required>
                </div>
                <div class="mb-3">
                    <label for="email" class="form-label">Email</label>
                    <input type="email" id="email" name="email" class="form-control shadow-none" placeholder="Votre Adresse Email" required>
                </div>
                <div class="mb-3">
                    <label for="message" class="form-label">Message</label>
                    <textarea id="message" name="message" class="form-control shadow-none" rows="6" placeholder="Entrer votre message ici" required></textarea>
                </div>
                <div class="text-center">
                    <button type="submit" class="btn btn-primary">Envoyer</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/detail_sujet.html
{% extends 'base.html' %}

{% block content %}
<div class="card mb-3 shadow-sm mt-5">
    <div class="card-header bg-primary text-white">
        <div class="card-title fs-3">{{ sujet.titre }}</div>
    </div>
    <div class="card-body bg-light text-dark">
        <p class="card-text"><i class="fas fa-layer-group"></i> <strong>Type:</strong> {{ sujet.get_type_sujet_display }}</p>
        <p class="card-text"><i class="fas fa-stream"></i> <strong>Filière:</strong> {{ sujet.get_filiere_display }}</p>
        <p class="card-text"><i class="fas fa-signal"></i> <strong>Niveau:</strong> {{ sujet.get_niveau_display }}</p>
        <p class="card-text"><i class="fas fa-book-open"></i> <strong>Cours:</strong> {{ sujet.nom_cours }}</p>
        <p class="card-text"><i class="fas fa-code"></i> <strong>Code du cours:</strong> {{ sujet.code_cours }}</p>
        <p class="card-text"><i class="fas fa-calendar-alt"></i> <strong>Année:</strong> {{ sujet.annee }}</p>
    </div>
    <div class="card-footer">
        <a href="{{ sujet.fichier.url }}" class="btn btn-success"><i class="fas fa-download"></i> Télécharger le sujet</a>
    </div>
</div>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Accueil - My Fax{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row align-items-center shadow">
        <div class="col-lg-3 order-lg-2">
            <img src="{% static 'img/main.png' %}" alt="My Fax, votre partenaire pour la réussite académique" class="img-fluid rounded">
        </div>
        <div class="col-lg-9 text-light order-lg-1">
            <h1 class="display-4 text-primary fw-bold mb-4">Votre Licence, Notre Mission</h1>
            <p class="lead">Optimisez votre parcours académique avec My Fax. Accédez à une bibliothèque complète de ressources pédagogiques pour exceller dans vos études et décrocher votre Licence avec brio.</p>
            <p class="lead">Explorez des sujets d'examen triés par discipline, niveau et année académique. Profitez de notre plateforme intuitive pour consulter ou télécharger le matériel nécessaire à votre succès.</p>
            
            <div class="d-flex gap-3 flex-wrap">
                <a class="btn btn-primary btn-lg" href="{% url 'search' %}">
                    <i class="bi bi-search"></i> Découvrir les ressources
                </a>
                <a class="btn btn-outline-secondary btn-lg" href="{% url 'propos' %}">
                    <i class="bi bi-info-circle"></i> À propos de My Fax
                </a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/liste_sujets.html
{% extends 'base.html' %}

{% block content %}
<!-- Barre de recherche -->
<div class="d-flex justify-content-end">
    <form action="{% url 'recherche_sujet' %}" method="get" class="search-form">
        <input class="search-input" type="search" placeholder="Rechercher un sujet" aria-label="Recherche" name="q" required>
        <button class="search-button" type="submit"><i class="fas fa-search"></i></button>
    </form>
</div>
<!-- Titre de la page -->
<h2 class="fw-bold text-primary text-center mt-5 mb-4">Liste des Sujets</h2>

<div class="alert alert-primary">
    {% if query %}
    <div class="lead">Résultats pour <span class="text-warning">{{ query }}</span></div>
    {% elif filiere_choisie %}
    <div class="lead">Résultats pour <span class="text-warning"> {{ type_sujet_choisi }}: {{ filiere_choisie }} - {{ niveau_choisi }}</span></div>
    {% else %}
    <div class="lead">Explorez notre collection complète de sujets. Utilisez la barre de recherche ci-dessus pour filtrer les résultats selon vos intérêts.</div>
    {% endif %}
</div>    

<!-- Cartes des sujets -->
<div class="row">
    {% for sujet in page_obj %}
    <div class="col-md-4 mb-3">
        <div class="card h-100 shadow">
            <div class="card-body">
                <h4 class="card-title">{{ sujet.titre }}</h4>
                <h5 class="card-subtitle mb-2 text-muted">{{ sujet.code_cours }}</h5>
                <a href="{% url 'detail_sujet' sujet.id %}" class="btn btn-primary">Voir les détails</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<!-- Pagination links -->
<div class="containner">
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
                <a href="?page=1">« première</a>
                <a href="?page={{ page_obj.previous_page_number }}">précédente</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} sur {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">suivante</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">dernière »</a>
            {% endif %}
        </span>
    </div>
</div>
{% endblock %}

templates/pricing.html
{% extends 'base.html' %}

{% block title %}Tarifs - My Fax{% endblock %}

{% block content %}
<div class="container py-3">
    <div class="row justify-content-center py-4">
        <div class="col-md-8 text-center">
            <h1 class="display-5 fw-bolder text-primary">Nos tarifs</h1>
            <p class="lead font-italic text-light">Découvrez nos tarifs les plus abordables possible</p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4 my-1">
            <div class="card shadow rounded rounded-2 p-4">
                <div class="card-header w-100 bg-light text-center">
                    <h3 class="fw-bold text-dark">FREE</h3>
                    <span class="font-italic text-primary fw-bolder">0 XAF</span>
                </div>
                <div class="card-body">
                    <ul class="list-group">
                        <li class="mb-2 list-unstyled">
                            <a href="" class="plan-text align-items-center text-decoration-none">
                                <i class="fa fa-certificate text-success"></i>
                                <span>Epreuves d'examens</span>
                            </a>
                        </li>
                        <li class="mb-2 list-unstyled">
                            <a href="" class="plan-text align-items-center text-decoration-none">
                                <i class="fa fa-certificate text-success"></i>
                                <span>Explication de concepts et de théories</span>
                            </a>
                        </li>
                        <li class="mb-2 list-unstyled">
                            <a href="" class="plan-text align-items-center text-decoration-none">
                                <i class="fa fa-certificate text-success"></i>
                                <span>5 Exercices par jour sans corrigé</span>
                            </a>
                        </li>
                        <li class="mb-2 list-unstyled">
                            <a href="" class="plan-text align-items-center text-decoration-none">
                                <i class="fa fa-certificate text-danger"></i>
                                <span>Corrigés d'epreuves</span>
                            </a>
                        </li>
                        <li class="mb-2 list-unstyled">
                            <a href="" class="plan-text align-items-center text-decoration-none">
                                <i class="fa fa-certificate text-danger"></i>
                                <span>Quizz interactifs</span>
                            </a>
                        </li>
                        <li class="mb-2 list-unstyled">
                            <a href="" class="plan-text align-items-center text-decoration-none">
                                <i class="fa fa-certificate text-danger"></i>
                                <span>Videos explicatives</span>
                            </a>
                        </li>
                        <li class="mb-2 list-unstyled">
                            <a href="" class="plan-text align-items-center text-decoration-none">
                                <i class="fa fa-certificate text-danger"></i>
                                <span>Fiches de travaux dirigés</span>
                            </a>
                        </li>
                        <li class="mb-2 list-unstyled">
                            <a href="" class="plan-text align-items-center text-decoration-none">
                                <i class="fa fa-certificate text-danger"></i>
                                <span>Fiches de révision de cours</span>
                            </a>
                        </li>
                        <li class="mb-2 list-unstyled">
                            <a href="" class="plan-text align-items-center text-decoration-none">
                                <i class="fa fa-certificate text-danger"></i>
                                <span>Teacher AI (l'enseignant ai puissant) </span>
                            </a>
                        </li>
                        <li class="mb-2 mt-3 list-unstyled">
                            <a href="" class="w-100 btn btn-dark shadow-none ">
                               Souscrire
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-4 my-1">
            <div class="card shadow rounded rounded-2 p-4 border border-2 border-success">
                <div class="card-header w-100 bg-light text-center">
                    <h3 class="fw-bold text-success">PRO</h3>
                    <span class="font-italic text-primary fw-bolder">10.000 XAF</span>
                    <p class="fw-bolder mt-3 text-uppercase text-danger">Recommandé</p>
                </div>
                <div class="card-body">
                    <ul class="list-group">
                        <li class="mb-2 list-unstyled">
                            <a href="" class="plan-text align-items-center text-decoration-none">
                                <i class="fa fa-certificate text-success"></i>
                                <span>Epreuves d'examens</span>
                            </a>
                        </li>
                        <li class="mb-2 list-unstyled">
                            <a href="" class="plan-text align-items-center text-decoration-none">
                                <i class="fa fa-certificate text-success"></i>
                                <span>Corrigés d'epreuves</span>
                            </a>
                        </li>
                        <li class="mb-2 list-unstyled">
                            <a href="" class="plan-text align-items-center text-decoration-none">
                                <i class="fa fa-certificate text-success"></i>
                                <span>Explication de concepts et de théories</span>
                            </a>
                        </li>
                        <li class="mb-2 list-unstyled">
                            <a href="" class="plan-text align-items-center text-decoration-none">
                                <i class="fa fa-certificate text-success"></i>
                                <span>5 Exercices par jour avec corrigé</span>
                            </a>
                        </li>
                        <li class="mb-2 list-unstyled">
                            <a href="" class="plan-text align-items-center text-decoration-none">
                                <i class="fa fa-certificate text-success"></i>
                                <span>Quizz interactifs</span>
                            </a>
                        </li>
                        <li class="mb-2 list-unstyled">
                            <a href="" class="plan-text align-items-center text-decoration-none">
                                <i class="fa fa-certificate text-success"></i>
                                <span>Videos explicatives</span>
                            </a>
                        </li>
                        <li class="mb-2 list-unstyled">
                            <a href="" class="plan-text align-items-center text-decoration-none">
                                <i class="fa fa-certificate text-danger"></i>
                                <span>Fiches de travaux dirigés</span>
                            </a>
                        </li>
                        <li class="mb-2 list-unstyled">
                            <a href="" class="plan-text align-items-center text-decoration-none">
                                <i class="fa fa-certificate text-danger"></i>
                                <span>Fiches de révision de cours</span>
                            </a>
                        </li>
                        <li class="mb-2 list-unstyled">
                            <a href="" class="plan-text align-items-center text-decoration-none">
                                <i class="fa fa-certificate text-danger"></i>
                                <span>Teacher AI (l'enseignant ai puissant) </span>
                            </a>
                        </li>
                        <li class="mb-2 mt-3 list-unstyled">
                            <a href="" class="w-100 btn btn-success shadow-none">
                               Souscrire
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-4 my-1">
            <div class="card shadow rounded rounded-2 p-4">
                <div class="card-header w-100 bg-light text-center">
                    <h3 class="fw-bold text-warning">GOLD</h3>
                    <span class="font-italic text-primary fw-bolder">20.000 XAF</span>
                </div>
                <div class="card-body">
                    <ul class="list-group">
                        <li class="mb-2 list-unstyled">
                            <a href="" class="plan-text align-items-center text-decoration-none">
                                <i class="fa fa-certificate text-success"></i>
                                <span>Epreuves d'examens</span>
                            </a>
                        </li>
                        <li class="mb-2 list-unstyled">
                            <a href="" class="plan-text align-items-center text-decoration-none">
                                <i class="fa fa-certificate text-success"></i>
                                <span>Corrigés d'epreuves</span>
                            </a>
                        </li>
                        <li class="mb-2 list-unstyled">
                            <a href="" class="plan-text align-items-center text-decoration-none">
                                <i class="fa fa-certificate text-success"></i>
                                <span>Explication de concepts et de théories</span>
                            </a>
                        </li>
                        <li class="mb-2 list-unstyled">
                            <a href="" class="plan-text align-items-center text-decoration-none">
                                <i class="fa fa-certificate text-success"></i>
                                <span>5 Exercices par jour avec corrigé</span>
                            </a>
                        </li>
                        <li class="mb-2 list-unstyled">
                            <a href="" class="plan-text align-items-center text-decoration-none">
                                <i class="fa fa-certificate text-success"></i>
                                <span>Quizz interactifs</span>
                            </a>
                        </li>
                        <li class="mb-2 list-unstyled">
                            <a href="" class="plan-text align-items-center text-decoration-none">
                                <i class="fa fa-certificate text-success"></i>
                                <span>Videos explicatives</span>
                            </a>
                        </li>
                        <li class="mb-2 list-unstyled">
                            <a href="" class="plan-text align-items-center text-decoration-none">
                                <i class="fa fa-certificate text-success"></i>
                                <span>Fiches de travaux dirigés</span>
                            </a>
                        </li>
                        <li class="mb-2 list-unstyled">
                            <a href="" class="plan-text align-items-center text-decoration-none">
                                <i class="fa fa-certificate text-success"></i>
                                <span>Fiches de révision de cours</span>
                            </a>
                        </li>
                        <li class="mb-2 list-unstyled">
                            <a href="" class="plan-text align-items-center text-decoration-none">
                                <i class="fa fa-certificate text-success"></i>
                                <span>Teacher AI (l'enseignant ai puissant) </span>
                            </a>
                        </li>
                        <li class="mb-2 mt-3 list-unstyled">
                            <a href="" class="w-100 btn btn-warning shadow-none">
                               Souscrire
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/propos.html
{% extends 'base.html' %}
{% load static %}

{% block title %}À propos - My Fax{% endblock %}

{% block content %}
<div class="row flex-lg-row-reverse align-items-center g-5 py-5 shadow">
    <div class="col-lg-3">
        <img src="{% static 'img/about-us.png' %}" class="d-block mx-auto img-fluid rounded" alt="Notre équipe My Fax" loading="lazy">
    </div>
    <div class="col-lg-9 text-light">
        <h1 class="display-4 fw-bold text-primary mb-3">Notre Histoire, Votre Avenir</h1>
        <p class="lead">Fondé par des passionnés de l'éducation, My Fax est né de la volonté de révolutionner l'apprentissage universitaire. Nous mettons à votre disposition des outils innovants pour une préparation optimale à la Licence.</p>
        <p class="lead">Notre plateforme est le fruit d'une collaboration étroite entre experts pédagogiques et technologues, tous animés par le désir de contribuer à votre succès académique.</p>
        <p class="lead">Chez My Fax, nous valorisons l'excellence et l'accessibilité. Découvrez comment nous pouvons vous accompagner dans la réalisation de vos objectifs éducatifs.</p>
        <div class="d-flex gap-3 mt-4">
            <a class="btn btn-success btn-lg" href="#">Notre équipe</a>
            <a class="btn btn-outline-primary btn-lg" href="#">Notre mission</a>
        </div>
    </div>
</div>
<hr class="text-light">
<div class="row align-items-center shadow">
    <div class="col-lg-9 text-light">
        <h2 class="fw-bold text-primary">Pourquoi choisir My Fax ?</h2>
        <p class="lead">Notre engagement envers l'excellence académique et notre approche personnalisée de l'enseignement nous distinguent. Voici quelques raisons de nous faire confiance :</p>
        <ul class="list-unstyled mt-4">
            <li class="mb-3"><i class="bi bi-check-circle-fill text-success"></i> Une bibliothèque riche et constamment mise à jour</li>
            <li class="mb-3"><i class="bi bi-check-circle-fill text-success"></i> Des outils d'apprentissage interactifs et engageants</li>
            <li class="mb-3"><i class="bi bi-check-circle-fill text-success"></i> Un soutien personnalisé pour chaque étudiant</li>
            <li class="mb-3"><i class="bi bi-check-circle-fill text-success"></i> Une communauté d'étudiants et d'experts dédiée</li>
        </ul>
        <a class="btn btn-primary btn-lg mt-4" href="#">Découvrez nos services</a>
    </div>
</div>
{% endblock %}